[package]
name = "qst"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy-table = "7.0"
regex = "1.5"
lazy_static = "1.3.0"
clap = { version = "4.3.4", features = ["derive"] }
